#!/bin/bash

PR_NUMBER=$(hub pr list L|awk {'print $1'}|cut -d# -f2)

git checkout master
git fetch origin refs/pull/$PR_NUMBER/head

git merge FETCH_HEAD --no-ff -m "Merge pull request #$PR_NUMBER"
git push
